#database connect msg
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 6000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    #close thymeleaf cache
  thymeleaf:
    cache: false
    #redis config
  redis:
    host: 127.0.0.1
    #QQ email config
  mail:
    host: smtp.qq.com
    username: yne2213@qq.com
    password: dufcbwnnkwyibcfc
    default-encoding: UTF-8
    #RabbitMQ config
  rabbitmq:
    host: localhost
    username: guest
    password: guest
#add prefix
server:
  servlet:
    context-path: /work-task-manage
#mybatis config
mybatis:
  mapper-locations: classpath:com/example/demo/dao/*Mapper.xml
  config-location: classpath:mybatis-config.xml
#logging:
#  level:
#    com:
#      example:
#        demo:
#          dao: debug
